# Generated by Django 5.0.7 on 2024-08-01 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_userprofile_user_user_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to='user_management.userprofile', to_field='whatsapp_number'),
        ),
    ]
