# Generated by Django 5.0.7 on 2024-08-01 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_user_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(default=uuid.uuid4, max_length=15, unique=True),
        ),
    ]
