# Generated by Django 5.0.7 on 2024-08-01 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_userprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to='user_management.userprofile', to_field='whatsapp_number'),
        ),
    ]
