# Generated by Django 5.0.7 on 2025-07-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_remove_user_phone_number_remove_user_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
