# Generated by Django 5.0.7 on 2025-07-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
