# Generated by Django 5.0.7 on 2025-07-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_remove_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_plan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
