# Generated by Django 5.0.7 on 2025-07-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_transaction_reference_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestment',
            name='amount',
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.transaction'),
        ),
    ]
