# Generated by Django 5.0.7 on 2025-07-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_remove_userinvestment_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvestment',
            old_name='end_date',
            new_name='due_date',
        ),
    ]
